# Generated by Django 4.1.5 on 2023-01-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=300)),
                ('channel_id', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=6000, null=True)),
                ('publishedDateTime', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=600, null=True)),
                ('channel_title', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('thumbnailsUrls', models.URLField()),
            ],
        ),
    ]
